CREATE TABLE IF NOT EXISTS usersinroles (
  username VARCHAR (200) REFERENCES users (username) ON DELETE CASCADE ON UPDATE CASCADE,
  role VARCHAR(100) REFERENCES roles (role) ON DELETE CASCADE ON UPDATE CASCADE,
  rev INT NOT NULL DEFAULT 0,
  PRIMARY KEY (username, role)
);